//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonManagerConsole.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PersonManagerConsole.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] FakeDB_Binary {
            get {
                object obj = ResourceManager.GetObject("FakeDB_Binary", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id;Name;DateOfBirth;Email
        ///1;Eloisa Grady;1945. 06. 01. 0:00:00;kenyatta@reingertoy.name
        ///2;Isom Barton;1946. 07. 26. 0:00:00;sigmund@hodkiewicz.biz
        ///3;Wilton Gaylord;1994. 06. 10. 0:00:00;oda_vandervort@prohaskadietrich.uk
        ///4;Ms. Beth Emard;1985. 03. 29. 0:00:00;marques@runolfssonwolf.us
        ///5;Helmer VonRueden&apos;s;1988. 05. 06. 0:00:00;emery.fisher@smithambashirian.com
        ///6;Alessia Mayert;1942. 12. 10. 0:00:00;mayra_jast@parisian.us
        ///7;Oran Robel;1947. 03. 11. 0:00:00;maximilian_swaniawski@borer.us
        ///8;Laurence Hu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FakeDB_CSV {
            get {
                return ResourceManager.GetString("FakeDB_CSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] FakeDB_json {
            get {
                object obj = ResourceManager.GetObject("FakeDB_json", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] FakeDB_min_json {
            get {
                object obj = ResourceManager.GetObject("FakeDB_min_json", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] FakeDB_toml {
            get {
                object obj = ResourceManager.GetObject("FakeDB_toml", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id,Name,DateOfBirth,Email
        ///1,Jerod Rueckers,1972. 10. 02. 0:00:00,corenes@bodeanderson.name
        ///2,Arlie Ledner,1963. 04. 22. 0:00:00,tristian_macejkovic@steuber.us
        ///3,Mr. Gaylord Treutel,1977. 07. 08. 0:00:00,beverly.schaden@kilback.com
        ///4,Dane Romaguera,1969. 08. 19. 0:00:00,kayla@mayersmitham.us
        ///5,Casimer Flatley MD,1996. 08. 09. 0:00:00,destini.green@leffler.biz
        ///6,Luna Bognars,1955. 02. 04. 0:00:00,maiya_carroll@leschkovacek.ca
        ///7,Dayana Lesch,1955. 03. 29. 0:00:00,joyce@sanford.com
        ///8,Hunter Mills,1942.  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FakeDB_txt {
            get {
                return ResourceManager.GetString("FakeDB_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ArrayOfPerson xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Person&gt;
        ///    &lt;Id&gt;1&lt;/Id&gt;
        ///    &lt;Name&gt;Amie Rogahn V&lt;/Name&gt;
        ///    &lt;DateOfBirth&gt;2004-02-26T00:00:00+01:00&lt;/DateOfBirth&gt;
        ///    &lt;Email&gt;adrianna@lockman.info&lt;/Email&gt;
        ///  &lt;/Person&gt;
        ///  &lt;Person&gt;
        ///    &lt;Id&gt;2&lt;/Id&gt;
        ///    &lt;Name&gt;Bernita Beatty&lt;/Name&gt;
        ///    &lt;DateOfBirth&gt;1963-09-30T00:00:00+02:00&lt;/DateOfBirth&gt;
        ///    &lt;Email&gt;madelyn.bogisich@ondrickaschroeder.ca&lt;/Email&gt;
        ///  &lt;/Pe [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FakeDB_xml {
            get {
                return ResourceManager.GetString("FakeDB_xml", resourceCulture);
            }
        }
    }
}
